#!/bin/sh
git config user.email "pethermoreno@gmail.com"
git config user.name "Petherson Moreno"
#meta loop 'ls -l'
meta loop 'git config user.email "pethermoreno@gmail.com"'
meta loop 'git config user.name "Petherson Moreno"'