ARG DEBIAN_CODE_NAME
ARG PYTHON_VERSION
FROM python:${PYTHON_VERSION}-${DEBIAN_CODE_NAME} as pjsua2-build
LABEL org.opencontainers.image.authors="Petherson Moreno <pethermoreno@gmail.com>"
ARG PJSIP_VERSION
ENV SIP_ROOT_DIR=/usr

RUN apt-get update -qq && \
    DEBIAN_FRONTEND=noninteractive \
    apt-get install -y --no-install-recommends \
        build-essential \
        ca-certificates \
        curl \
        libgsm1-dev \
        libspeex-dev \
        libspeexdsp-dev \
        libssl-dev \
        libsrtp2-dev \
        libyuv-dev \
        portaudio19-dev \
        swig \
        ffmpeg \
        python3-av \
        pulseaudio \
        alsa-utils \
        && apt-get purge -y --auto-remove \
        && rm -rf /var/lib/apt/lists/*

RUN cat <<EOF | tee /tmp/pjsip_config_site.h
#define PJ_DEBUG    0
#define PJ_TIMER_DEBUG  0
#define PJ_HAS_IPV6 1
EOF

RUN mkdir /tmp/src-pjsip && \
    cd /tmp/src-pjsip && \
        curl -sL https://github.com/pjsip/pjproject/archive/refs/tags/${PJSIP_VERSION}.tar.gz | \
            tar --strip-components 1 -xz && \
    mv /tmp/pjsip_config_site.h pjlib/include/pj/config_site.h && \
    export CFLAGS="-fPIC -O2 -DNDEBUG" && \
    ./configure \
        --prefix=$SIP_ROOT_DIR \
        --with-external-speex \
        --with-external-srtp \
        --with-external-gsm \
        --with-external-yuv \
        --enable-shared \
        --disable-opencore-amr \
        --disable-video && \
    make dep && \
    make && \
    make install && \
    sed -E 's/LANG = python java/LANG = python/g' -i pjsip-apps/src/swig/Makefile && \
    cd pjsip-apps/src/swig/python && \
    make && \
    python setup.py install && \
    rm -rf /tmp/src-pjsip

CMD ["/bin/bash"]