version: '3'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: pokemontrainer
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - ./.volumes/mongodb:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - mongo_network

networks: 
    mongo_network:
      driver: bridge