parser: babel-eslint

env:
  browser: true
  jest: true

plugins:
  - react
  - jsx-a11y
  - import

extends:
  - airbnb

rules:
  react/jsx-filename-extension:
    - error
    - extensions:
        - .js
        - .jsx
  global-require: off
  import/prefer-default-export: off
  no-unused-expressions:
    - error
    - allowTaggedTemplates: true
  jsx-a11y/label-has-associated-control: off
  jsx-a11y/label-has-for: off

settings:
  import/resolver:
    webpack:
      config: config/webpack.config.resolve.alias.js
