const ADD_SHIPLIST = 'app/shipLists/ADD_SHIPLIST';
const REMOVE_SHIPLIST = 'app/shipLists/REMOVE_SHIPLIST';
const EDIT_SHIPLIST = 'app/shipLists/EDIT_SHIPLIST';
const GET_SHIPLISTS = 'app/shipLists/GET_SHIPLISTS';
const UPDATE_SHIPLIST_SELECTED = 'app/shipLists/UPDATE_SHIPLIST_SELECTED';
const ADD_SHIPLIST_ITEM = 'app/shipLists/ADD_SHIPLIST_ITEM';
const EDIT_SHIPLIST_ITEM = 'app/shipLists/EDIT_SHIPLIST_ITEM';

export default {
  ADD_SHIPLIST,
  REMOVE_SHIPLIST,
  EDIT_SHIPLIST,
  GET_SHIPLISTS,
  UPDATE_SHIPLIST_SELECTED,
  ADD_SHIPLIST_ITEM,
  EDIT_SHIPLIST_ITEM,
};
