const ADD_PRODUCT_TYPE = 'app/productTypes/ADD_PRODUCT_TYPE';
const REMOVE_PRODUCT_TYPE = 'app/productTypes/REMOVE_PRODUCT_TYPE';
const EDIT_PRODUCT_TYPE = 'app/productTypes/EDIT_PRODUCT_TYPE';
const GET_PRODUCT_TYPES = 'app/productTypes/GET_PRODUCT_TYPES';

export default {
  ADD_PRODUCT_TYPE,
  REMOVE_PRODUCT_TYPE,
  EDIT_PRODUCT_TYPE,
  GET_PRODUCT_TYPES,
};
