version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing dependencies
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
artifacts:
  files:
    - package.json
    - package-lock.json
    - tsconfig.build.json
    - 'node_modules/**/*'
    - 'templates/**/*'
    - 'dist/**/*'
    - README.md