const EDIT_USER_INFO = "app/user/EDIT_USER_INFO";
const SEND_EMAIL_VERIFICATION = "app/user/SEND_EMAIL_VERIFICATION";
const GET_USER_INFO = "app/user/GET_USER_INFO";
const EDIT_USER_CONFIG = "app/user/EDIT_USER_CONFIG";
const GET_USER_CONFIG = "app/user/GET_USER_CONFIG";

export default {
  EDIT_USER_INFO,
  SEND_EMAIL_VERIFICATION,
  GET_USER_INFO,
  EDIT_USER_CONFIG,
  GET_USER_CONFIG
};
