<?php
    $_helper = $this->helper('catalog/output');
    $productId = $this->getProductId();
    $_product = Mage::getModel('catalog/product')->load($productId); //load the product
    $_imageWidth = 100;
    $_imageHeight = 100;
?>
<div class="separate_product_view">
    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imageWidth,$_imageHeight); ?>" width="<?php echo $_imageWidth; ?>" height="<?php echo $_imageHeight; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
    <div class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></div>

    <?php if($_product->getRatingSummary()): ?>
    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
    <?php endif; ?>
    <?php echo $this->getPriceHtml($_product, true) ?>

    
    <div class="sp"></div>
</div>
