name: Build Container Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Build image with Kaniko
        uses: docker://gcr.io/kaniko-project/executor:debug
        with:
          entrypoint: sh
          args: -c "export HOME=/kaniko && echo '{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"${{ secrets.DOCKER_HUB_AUTHENTICATION }}\"}}}' > $HOME/.docker/config.json && $HOME/executor --dockerfile Dockerfile --destination '${{ secrets.DOCKER_HUB_REPOSITORY }}:${{ github.run_number }}' --destination '${{ secrets.DOCKER_HUB_REPOSITORY }}:latest' --context $(pwd)"