name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  # 
  PJSIP_VERSION: 2.15.1
  DEBIAN_CODE_NAME: bookworm
  PYTHON_VERSION: 3.11.12

jobs:
  build_push_dockerhub:
    name: Build and Push Docker Image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}"
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest, ${{ env.IMAGE_NAME }}:${{ env.PJSIP_VERSION }}-python${{ env.PYTHON_VERSION }}
          build-args: |
            PJSIP_VERSION=${{ env.PJSIP_VERSION }}
            DEBIAN_CODE_NAME=${{ env.DEBIAN_CODE_NAME }}
            PYTHON_VERSION=${{ env.PYTHON_VERSION }}
