name: Build Docker Image

on:
  pull_request:
    branches: [ "main" ]

env:
  PJSIP_VERSION: 2.15.1
  DEBIAN_CODE_NAME: bookworm
  PYTHON_VERSION: 3.11.12

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build the Docker image
        run: docker build --build-arg PJSIP_VERSION=${{ env.PJSIP_VERSION }} --build-arg DEBIAN_CODE_NAME=${{ env.DEBIAN_CODE_NAME }} --build-arg PYTHON_VERSION=${{ env.PYTHON_VERSION }} .
